[main]
font=monospace:size=13
pad=20x15

[colors-dark]
# Base
background=181616
foreground=d4be98

# Selection
selection-background=2e2a2a
selection-foreground=d4be98

# Normal (ANSI 0-7)
regular0=181616  # black
regular1=b53535  # red
regular2=b4c76e  # green
regular3=e7bb5c  # yellow
regular4=7b8fd4  # blue
regular5=b06880  # magenta
regular6=689d8a  # cyan
regular7=c2c2c2  # white

# Bright (ANSI 8-15)
bright0=2e2a2a   # bright black
bright1=c94040   # bright red
bright2=cad98a   # bright green
bright3=f0cc7a   # bright yellow
bright4=9aaae0   # bright blue
bright5=c8889a   # bright magenta
bright6=89b8a8   # bright cyan
bright7=d4be98   # bright white

[cursor]
style=block
blink=yes